### ISSUE TITLE
八字排盘计算结果有误

### ISSUE THREAD

**Issue by xavierzhu** [mattxlee/eightwords#2]
~/eightwords/build# ./eightwords -s calendar.db -y 2006 -m 1 -d 28 -H 23
乙酉 己丑 丁巳 庚子 

但是按wikipedia（https://zh.wikipedia.org/wiki/%E5%85%AB%E5%AD%97）
西元 | 2006年1月28日23:50
农历 | 丙戌年正月初一日子时
八字 | 乙酉年己丑月戊午日壬子时

日和时都对不上。

**Comment by mattxlee** [comment]
这个问题主要是因为阴历日历导致的，你可以查查看2016/1/28的阴历在数据库里是否正确。
